# PERSONAL EXTERNAL REPOSITORIES
[".config/nvim"]
url = "https://github.com/bayou-brogrammer/nvim"
type = "git-repo"

[".config/zsh"]
url = "https://github.com/bayou-brogrammer/zdotdir"
type = "git-repo"

#[".config/fish"]
#url = "https://github.com/bayou-brogrammer/fishconf"
#type = "git-repo"
